spring.application.name=FixLogAPi.git
spring.mvc.problemdetails.enabled=true
# Database connection settings
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fixLogDb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:123}
#spring.datasource.driver-class-name=org.postgresql.Driver
# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#flyway DB Migrations
spring.flyway.enabled=true
#spring.flyway.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fixLogDb}
#spring.flyway.user=${FLYWAY_USER}
#spring.flyway.password=${FLYWAY_PASSWORD}
#spring.sql.init.mode=always
logging.level.org.springframework.boot.autoconfigure=INFO
